# Copyright 2026 SARC Suite Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
V1 pre-registration gate tests: the prereg-v1 tag exists, its tree
contains definitions only (no results), and every generated manifest
records that tag's commit sha.

SEED = 26313
"""
from __future__ import annotations

import json
import subprocess

import pytest

REQUIRED_PREREG_FILES = [
    "prereg/hypotheses.md",
    "prereg/seeds.json",
    "prereg/weights.json",
    "prereg/w2-workflow.md",
    "prereg/contamination.md",
    "prereg/renaming.md",
    "prereg/ch2-semantics.md",
    "schemas/evidence_line.schema.json",
]

# Paths that would indicate RESULTS (not definitions) leaking into the
# prereg-v1 tree — anything generated by running an experiment.
RESULT_PATH_MARKERS = (
    "out/metrics.json",
    "out/quality.json",
    "out/results/",
    "out/paper/",
    "paper4-composition-draft-v0.2-populated.md",
    "paper4-composition-draft-v0.3",
)


def _tag_exists(tag: str) -> bool:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", f"refs/tags/{tag}"],
        capture_output=True, text=True,
    )
    return result.returncode == 0


def _tree_files_at(ref: str) -> list:
    result = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", ref],
        capture_output=True, text=True, check=True,
    )
    return result.stdout.splitlines()


@pytest.mark.skipif(not _tag_exists("prereg-v1"), reason="prereg-v1 tag not created yet")
def test_prereg_v1_tag_contains_required_definitions():
    files = set(_tree_files_at("prereg-v1"))
    for required in REQUIRED_PREREG_FILES:
        assert required in files, f"prereg-v1 is missing required definition file: {required}"


@pytest.mark.skipif(not _tag_exists("prereg-v1"), reason="prereg-v1 tag not created yet")
def test_prereg_v1_tree_contains_no_results():
    files = _tree_files_at("prereg-v1")
    for f in files:
        for marker in RESULT_PATH_MARKERS:
            assert not f.startswith(marker) and f != marker, (
                f"prereg-v1 tree contains a results path ({f!r}) — "
                "the tag must contain definitions only"
            )


@pytest.mark.skipif(not _tag_exists("prereg-v1"), reason="prereg-v1 tag not created yet")
def test_prereg_v1_seeds_and_weights_well_formed():
    seeds_raw = subprocess.run(
        ["git", "show", "prereg-v1:prereg/seeds.json"], capture_output=True, text=True, check=True,
    ).stdout
    seeds = json.loads(seeds_raw)
    assert seeds["count"] == 30
    assert seeds["seeds"][0] == 26313
    assert len(set(seeds["seeds"])) == 30

    weights_raw = subprocess.run(
        ["git", "show", "prereg-v1:prereg/weights.json"], capture_output=True, text=True, check=True,
    ).stdout
    weights = json.loads(weights_raw)
    assert len(weights["weight_vectors"]) == 66
    assert weights["thresholds"] == [0.5, 0.6, 0.7, 0.8]
    for v in weights["weight_vectors"]:
        assert abs(sum(v.values()) - 1.0) < 1e-9


@pytest.mark.skipif(not _tag_exists("prereg-v1"), reason="prereg-v1 tag not created yet")
def test_manifest_records_prereg_v1_sha(tmp_path):
    from manifest import build_manifest
    import hashlib

    sha = hashlib.sha256(open("data/open_retail_daily.csv", "rb").read()).hexdigest()
    manifest = build_manifest(sha, 26313)
    prereg_sha = subprocess.run(
        ["git", "rev-list", "-n", "1", "prereg-v1"], capture_output=True, text=True, check=True,
    ).stdout.strip()
    assert "prereg_v1_sha" in manifest, "manifest.py must record the prereg-v1 commit sha (R-9.5/V1)"
    assert manifest["prereg_v1_sha"] == prereg_sha
