# Copyright 2026 SARC Suite Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Canonical generator for prereg/seeds.json. Run ONCE to produce the frozen
30-seed list; seeds.json is committed as the pre-registered artifact and
is never regenerated by this script again after prereg-v1 is tagged (that
would defeat the point of freezing it).

Method: first seed is 26313 (the artifact's existing SEED, kept as seed
index 0 for continuity with all prior CH1-CH4 results). The remaining 29
are drawn, without replacement, from a Mersenne Twister seeded by 26313
itself, over [1, 2**31 - 1] — fully deterministic and reproducible from
this file alone.
"""
import json
import random

FIRST_SEED = 26313
COUNT = 30


def generate() -> list:
    rng = random.Random(FIRST_SEED)
    seeds = [FIRST_SEED]
    seen = {FIRST_SEED}
    while len(seeds) < COUNT:
        candidate = rng.randint(1, 2**31 - 1)
        if candidate not in seen:
            seeds.append(candidate)
            seen.add(candidate)
    return seeds


if __name__ == "__main__":
    seeds = generate()
    assert len(seeds) == COUNT
    assert seeds[0] == FIRST_SEED
    assert len(set(seeds)) == COUNT
    print(json.dumps({"first_seed": FIRST_SEED, "count": COUNT, "seeds": seeds}, indent=2))
