#!/usr/bin/env python3
# Copyright 2026 SARC Suite Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
arXiv LaTeX conversion, non-negotiable #2: "Every citation in refs.bib is
generated from verified-citations.json, nothing else. No new references.
If a reference lacks a BibTeX-required field, derive it only from the
verified record's stored fields."

This script is that generator: it reads exactly verified-citations.json
(../verified-citations.json relative to this file) and writes exactly
one @misc entry per citation record. @misc is used uniformly -- not
@article or @inproceedings -- because those types conventionally expect
a journal/booktitle field this repo's verified records never fetched or
stored; inventing one (even a "standard" arXiv-preprint convention like
journal={arXiv preprint arXiv:...}) would be a field not derived from
the stored record, which the non-negotiable forbids. Every BibTeX field
below maps 1:1 to a verified-citations.json key:

  id           -> citation key (BibTeX entry key)
  first_author -> author
  title        -> title
  year         -> year
  doi          -> doi         (only if present in the record)
  arxiv_id     -> eprint + archivePrefix={arXiv}  (only if present)
  url          -> url
  verified_via -> note (audit trail: how/when this repo verified it)

Deterministic and idempotent: re-running with an unchanged
verified-citations.json produces a byte-identical refs.bib. Run this
script directly, or via `make -C paper-tex/.. arxiv` which regenerates
refs.bib on every build so it can never drift from verified-citations.json.
"""
from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
CITATIONS_PATH = SCRIPT_DIR.parent / "verified-citations.json"
OUT_PATH = SCRIPT_DIR / "refs.bib"

_BIB_ESCAPES = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
}


def _escape(value: str) -> str:
    return "".join(_BIB_ESCAPES.get(ch, ch) for ch in value)


def _entry(citation: dict) -> str:
    key = citation["id"]
    lines = [f"@misc{{{key},"]
    lines.append(f"  author = {{{_escape(citation['first_author'])}}},")
    lines.append(f"  title = {{{{{_escape(citation['title'])}}}}},")
    lines.append(f"  year = {{{citation['year']}}},")
    if "doi" in citation:
        lines.append(f"  doi = {{{citation['doi']}}},")
    if "arxiv_id" in citation:
        lines.append(f"  eprint = {{{citation['arxiv_id']}}},")
        lines.append("  archivePrefix = {arXiv},")
    lines.append(f"  url = {{{citation['url']}}},")
    lines.append(f"  note = {{{_escape(citation['verified_via'])}}},")
    lines[-1] = lines[-1].rstrip(",")  # no trailing comma on the last field
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    data = json.loads(CITATIONS_PATH.read_text())
    citations = data["citations"]
    header = (
        "% Generated by paper-tex/generate_refs_bib.py from verified-citations.json.\n"
        "% Do not hand-edit -- every field is derived from that file's stored\n"
        "% records alone (arXiv LaTeX conversion task, non-negotiable #2).\n"
        f"% {len(citations)} entries.\n\n"
    )
    return header + "\n\n".join(_entry(c) for c in citations) + "\n"


if __name__ == "__main__":
    text = generate()
    OUT_PATH.write_text(text)
    print(f"wrote {OUT_PATH} ({text.count('@misc')} entries)")
